export default {
    SET_ERROR: 'SET_ERROR',
    GET_ARTICLES: 'GET_ARTICLES',
    SET_ARTICLES: 'SET_ARTICLES',
    GET_PLACES: 'GET_PLACES',
    SET_PLACES: 'SET_PLACES',
    REMOVE_ARTICLE: 'REMOVE_ARTICLE',
    GET_ARTICLE: 'GET_ARTICLE',
    SET_ARTICLE: 'SET_ARTICLE',
};